# -*- coding: utf-8 -*-
"""annual final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfGJWcvOl4EsbWZINSmp3jg5viLcmjAA
"""

# Install first if needed
!pip install camelot-py pandas openpyxl pdfplumber
!apt-get install ghostscript -y

import camelot
import pandas as pd
from google.colab import files

PDF_FILE = "/content/Annual-Report-and-Form-20-F-2025.pdf.downloadasset.pdf"

# MANUAL PAGE NUMBERS
STATEMENT_PAGES = {
    "Income_Statement": "123",
    "Comprehensive_Statement_Income":"124",
    "Balance_Sheet": "125",
    "Cash_Flow": "128"
}

output_file = "Annual_Report_Financials.xlsx"

with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

    for sheet_name, page_no in STATEMENT_PAGES.items():

        try:

            tables = camelot.read_pdf(
                PDF_FILE,
                pages=page_no,
                flavor="stream"
            )

            if len(tables) == 0:
                print(f"No tables found on page {page_no}")
                continue

            combined_df = pd.concat(
                [table.df for table in tables],
                ignore_index=True
            )

            combined_df.to_excel(
                writer,
                sheet_name=sheet_name,
                index=False
            )

            print(f"Extracted {sheet_name}")

        except Exception as e:

            print(f"Error on page {page_no}: {e}")

print("Excel created!")

files.download(output_file)